### ISSUE TITLE
Pull request #57 broke build on OS X 10.9.1

### ISSUE THREAD

**Issue by gicmo** [G-Node/nix#61]
Forgot to include `<functional>` for `std::function`.

```
In file included from /Users/gicmo/Coding/G-Node/nix/src/Dimensions.cpp:10:
In file included from /Users/gicmo/Coding/G-Node/nix/include/nix/Dimensions.hpp:12:
/Users/gicmo/Coding/G-Node/nix/include/nix/base/ImplContainer.hpp:51:14: error: no type named 'function' in namespace 'std'
        std::function<bool(TENT)> filter) const
        ~~~~~^
/Users/gicmo/Coding/G-Node/nix/include/nix/base/ImplContainer.hpp:51:22: error: expected ')'
        std::function<bool(TENT)> filter) const
```
